In [ ]:
## callable instances
class A:
  def __init__(a):
    print(a)
  def __call__(self, b):
    return (f' I received the call, the message was {b} !!!')
aa =A()
print(f'this object is callable? {callable(aa)}, check it --> {aa("X")}')

this object is callable? True, check it -->  I received the call, the message was X !!!


In [ ]:
# Python Zen
import this

In [ ]:
# using *arg
def throw_party(host, *guests):
    print(host, 'is throwing a party!')
    for guest in guests:
        print(guest, 'has arrived.')
throw_party('Anika', 'Jethrow', 'Roxanne', 'Sadiyah', 'Andrei')

In [12]:
### unpacking
a,b,c,d = 1, *[2,3,4]
print(a,b,c,d)

a,b,c,d = [1,2,3,4]
print(a,b,c,d)

# these two are essentially the same
def ret():
  return [2,3,4]
def ret2():
  return 2,3,4

a,b,c,d = 1, *ret()
print(a,b,c,d)

a,b,c,d = 1, *ret2()
print(a,b,c,d)


# without star is necessary to specify with parenthesis
a,(b,c,d) = 1, ret2()
print(a,b,c,d)

def ret3():  
  return 1, ret() # also works with ret2()
a,(b,c,d) = ret3()
print(a,b,c,d)

print(*ret3()) # partial unpacking, because ret3() return a nested package

### packing
pack = ret2()
print(pack)

1 2 3 4
1 2 3 4
1 2 3 4
1 2 3 4
1 2 3 4
1 2 3 4
1 [2, 3, 4]
(2, 3, 4)


In [ ]:
#### LEARN about context managers
from contextlib import contextmanager
import sys, os

@contextmanager
def suppress_stdout():
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        try:  
            yield
        finally:
            sys.stdout = old_stdout
With this, you can use context management wherever you want to suppress output:

print("Now you see it")
with suppress_stdout():
    print("Now you don't")

4


# DL situations

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support 

def ill_defined_tester(truth,pred):
  y_true = np.array(truth)
  y_pred = np.array(pred)
  p, r, f, s = precision_recall_fscore_support(y_true, y_pred, average='macro')
  cmatrix = confusion_matrix(y_true, y_pred)
  print(f'Scores: p={p:.2f}; r={r:.2f}; f={f:.2f};')
  print("Confusion matrix:\n",cmatrix)

def label_diffs2(truth,pred):
  truth_set = set(truth)
  pred__set = set(pred)
  print(f'truth_set: {truth_set}')
  print(f'pred__set: {pred__set}')
  difft = pred__set - truth_set
  diffp = truth_set - pred__set
  if len(difft): print(f'unexpected labels predicted: {difft}')
  if len(diffp): print(f'not predicted labels: {diffp}')

def label_diffs(truth,pred):  
  difft = set(pred) - set(truth)
  diffp = set(truth) - set(pred)
  if len(difft): print(f'unexpected labels predicted: {difft}')
  if len(diffp): print(f'not predicted labels: {diffp}')  

def testing_ill_defined_predictions():
  truth= ['a','b',"c"]*2 # it generates ['a', 'b', 'c', 'a', 'b', 'c']

  # ill-defined predictions cases: precision
  print("\n\n1. ill-defined predictions cases: precision")

  print("\nb and c were not predicted")
  pred = ['a']*6 # because b and c were not predicted
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)

  print("\nb and c was not predicted")
  pred = ['a']*5 + ['b'] # because c was not predicted
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)

  # ill-defined predictions cases: recall
  print("\n\n2. ill-defined predictions cases: recall")
  print("\nthe model is predicting unexpected labels")
  pred= ['a']*3 + ['b'] + ['c']+ ['z'] # the model is predicting labels not present _in the current_ truth
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)


  # ill-defined predictions cases: precision and recall
  print("\n\n3. ill-defined predictions cases: precision and recall")
  print("\nthe model is predicting unexpected labels and missing expected ones")
  pred= ['a']*5 + ['z'] # the model is predicting labels not present _in the current_ truth
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)


  # no ill-defined predictions cases
  print("\n\n4. No ill-defined predictions cases")
  print("\nProbably a common scenario")
  pred = ['a']*4 + ['b'] + ['c'] # all labels in np.unique(truth) are predicted at least once
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)

  print("\nPerfect score: very uncommon scenario")
  pred = ['a', 'b', 'c', 'a', 'b', 'c'] # perfect score
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)

  print("\nEverything wrong, :')")
  pred= ['c','a',"b"]*2 # 
  ill_defined_tester(truth,pred)
  label_diffs(truth,pred)

testing_ill_defined_predictions()



1. ill-defined predictions cases: precision

b and c were not predicted
Scores: p=0.11; r=0.33; f=0.17;
Confusion matrix:
 [[2 0 0]
 [2 0 0]
 [2 0 0]]
not predicted labels: {'c', 'b'}

b and c was not predicted
Scores: p=0.13; r=0.33; f=0.19;
Confusion matrix:
 [[2 0 0]
 [2 0 0]
 [1 1 0]]
not predicted labels: {'c'}


2. ill-defined predictions cases: recall

the model is predicting unexpected labels
Scores: p=0.08; r=0.12; f=0.10;
Confusion matrix:
 [[1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 0 0 0]]
unexpected labels predicted: {'z'}


3. ill-defined predictions cases: precision and recall

the model is predicting unexpected labels and missing expected ones
Scores: p=0.10; r=0.25; f=0.14;
Confusion matrix:
 [[2 0 0 0]
 [2 0 0 0]
 [1 0 0 1]
 [0 0 0 0]]
unexpected labels predicted: {'z'}
not predicted labels: {'c', 'b'}


4. No ill-defined predictions cases

Probably a common scenario
Scores: p=0.83; r=0.67; f=0.67;
Confusion matrix:
 [[2 0 0]
 [1 1 0]
 [1 0 1]]

Perfect score: very uncommo

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
if len(set([0,1,2,1,4,5]) - set([0,1,2])): print("s")

s
